### ISSUE TITLE
Cannot Delete Jail

### ISSUE THREAD

**Issue by fsbruva** [fsbruva/thebrig#20]
When attempting to delete a jail, this error is received:
Catchable fatal error: Argument 1 passed to array_sort_key() must be of the type array, null given, called in /mnt/tank/briggy/conf/ext/thebrig/functions.inc on line 854 and defined in /etc/inc/array.inc on line 74

**Comment by alexey1234** [comment]
This faulrt we have if we have only 1 jail and try delete it.


2015-05-04 7:33 GMT+03:00 fsbruva <notifications@github.com>:

**Comment by alexey1234** [comment]
Repaired
