### ISSUE TITLE
Moving Thebrig causes undesirable data loss

### ISSUE THREAD

**Issue by sn3ak** [fsbruva/thebrig#21]
Please fix [this] (https://github.com/fsbruva/thebrig/blob/alcatraz/conf/ext/thebrig/functions.inc#L86)

Either add a warning to the page that all data is going to be removed, or remove that line, and tell people they need to go clean up the remains. or add a checkbox or some such.

**Comment by fsbruva** [comment]
I am sorry you had an issue. I never imagined that someone would attempt to move the brig once it contained jails. It is clearly a bug - next time, don't be afraid to submit a pull request!

**Comment by fsbruva** [comment]
Repaired. Thebrig's installation target folder will only be deleted if it's empty, after everything else is moved out.
