### ISSUE TITLE
Missing XML/Serializer in 10.1.0.2 beta

### ISSUE THREAD

**Issue by Chankster** [fsbruva/thebrig#24]
Updated to beta: 10.1.0.2 - Prescience (revision 1608)

Warning: require_once(XML/Serializer.php): failed to open stream: No such file or directory in /usr/local/www/ext/thebrig/extensions_thebrig.php on line 10 Fatal error: require_once(): Failed opening required 'XML/Serializer.php' (include_path='.:/etc/inc:/usr/local/www') in /usr/local/www/ext/thebrig/extensions_thebrig.php on line 10

**Comment by alexey1234** [comment]
I repair it, and I'll upload today

**Comment by alexey1234** [comment]
Repaired

**Comment by AndreasGabel** [comment]
I receive the above error message. Fresh install of NAS4Free 10.1.0.2 - Prescience (revision 1608):

Warning: require_once(XML/Serializer.php): failed to open stream: No such file or directory in /usr/local/www/ext/thebrig/extensions_thebrig.php on line 10 Fatal error: require_once(): Failed opening required 'XML/Serializer.php' (include_path='.:/etc/inc:/usr/local/www') in /usr/local/www/ext/thebrig/extensions_thebrig.php on line 10
