### ISSUE TITLE
thebrig extensions not working

### ISSUE THREAD

**Issue by vdpollm** [fsbruva/thebrig#25]
hi,
after i click on Extensions->TheBrig, i get the following in a webpage:
Warning: require_once(XML/Serializer.php): failed to open stream: No such file or directory in /usr/local/www/ext/thebrig/extensions_thebrig.php on line 10 Fatal error: require_once(): Failed opening required 'XML/Serializer.php' (include_path='.:/etc/inc:/usr/local/www') in /usr/local/www/ext/thebrig/extensions_thebrig.php on line 10

was working fine, not sure what i did wrong - please point me in the right direction?

regards
Marc

**Comment by alexey1234** [comment]
For 9.3 or 10.1 based Nas4Free please use alcatraz branch.  See commit https://github.com/fsbruva/thebrig/commit/787287591bd6ec61092e1c5d4258ec98d333fd5d

**Comment by vdpollm** [comment]
hi alexey1234
i download thebrig_install.sh (Alcatraz branch version), chmod a+x it, and run:
sh thebrig_install.sh /mnt/data/Jail 2. i get:
"thebrig_install.sh: 4: Syntax error: newline unexpected (expecting word)" as the output.
i restarted the box, just to clear out the /tmp folder.
did i do something wrong?
regards
Marc

**Comment by alexey1234** [comment]
Hi, Marc
You need download install script from alcatraz location
fetch https://raw.githubusercontent.com/fsbruva/thebrig/alcatraz/thebrig_install.sh
then execute 
sh thebrig_install.sh /mnt/data/Jail 3
Attention : must be 3 instead 2 for install alcatraz

**Comment by vdpollm** [comment]
thank you alexey1234 that worked like a charm.

**Comment by AndreasGabel** [comment]
Tried this as well, still get the Warning mentioned above on 10.2. :/

Edit: added jail_enable=YES to /etc/rc.conf, then rebooted, then installed again and it worked.
