### ISSUE TITLE
thebrig (Alcatraz) on NAS4Free 10.1.0.2 (1731): "Start on boot" not working

### ISSUE THREAD

**Issue by timhansinger** [fsbruva/thebrig#26]
Hello,

I recently updated to NAS4Free 10.1.0.2 (1731) and thebrig Alcatraz. However, now the option "Start on boot" isn't working anymore. The jail just doesn't start. I even created a completely new jail, same issue.

Is this known? Is there a command line I could use to start the jail from an SSH console also?

Thank you very much.

Best regards
Tim

**Comment by fsbruva** [comment]
Good afternoon,
I have not tested thebrig with 10.x yet. I am currently in the middle of a move from Alaska to Virginia. Once I get situated, I will have time to finish up a few loose ends on alcatraz and begin testing on 10.
Matt-------- Original message --------From: timhansinger notifications@github.com Date: 08/05/2015  07:23  (GMT-05:00) To: fsbruva/thebrig thebrig@noreply.github.com Subject: [thebrig] thebrig (Alcatraz) on NAS4Free 10.1.0.2 (1731): "Start on
  boot" not working (#26) 
Hello,

I recently updated to NAS4Free 10.1.0.2 (1731) and thebrig Alcatraz. However, now the option "Start on boot" isn't working anymore. The jail just doesn't start. I even created a completely new jail, same issue.

Is this known? Is there a command line I could use to start the jail from an SSH console also?

Thank you very much.

Best regards

Tim

**Comment by alexey1234** [comment]
Start on boot work for me on 3 servers without any problem
Need check option "Allow start all jails" on first page

**Comment by timhansinger** [comment]
Thank you alexey1234. That did the trick.
I don't know how I missed that option.

Thank you again!
